### ISSUE TITLE
Please add documentation with instructions for compilation

### ISSUE THREAD

**Issue by K0nne** [NETWAYS/icinga-powershell-connector#4]
Hello,

right now I want to test a PR in this repo. Unfortunately there are no compilation instructions. Could you please add this?

**Comment by lazyfrosch** [comment]
This is a very very simple go program, there is simply no need for specific instructions.

Here is an example howto:
https://www.digitalocean.com/community/tutorials/how-to-build-and-install-go-programs

Also see:
https://github.com/NETWAYS/icinga-powershell-connector/blob/main/.github/workflows/go.yml#L28-L29
